// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/example-org/platform/backend/inventory/app/inventory/access"
)

// NewAuditStorageMock creates a new instance of AuditStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditStorageMock {
	mock := &AuditStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditStorageMock is an autogenerated mock type for the AuditStorage type
type AuditStorageMock struct {
	mock.Mock
}

type AuditStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditStorageMock) EXPECT() *AuditStorageMock_Expecter {
	return &AuditStorageMock_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type AuditStorageMock
func (_mock *AuditStorageMock) Append(ctx context.Context, event access.AuditEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.AuditEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditStorageMock_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type AuditStorageMock_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event access.AuditEvent
func (_e *AuditStorageMock_Expecter) Append(ctx interface{}, event interface{}) *AuditStorageMock_Append_Call {
	return &AuditStorageMock_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *AuditStorageMock_Append_Call) Run(run func(ctx context.Context, event access.AuditEvent)) *AuditStorageMock_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(access.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditStorageMock_Append_Call) Return(err error) *AuditStorageMock_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditStorageMock_Append_Call) RunAndReturn(run func(ctx context.Context, event access.AuditEvent) error) *AuditStorageMock_Append_Call {
	_c.Call.Return(run)
	return _c
}

// NewReservationStorageMock creates a new instance of ReservationStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationStorageMock {
	mock := &ReservationStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReservationStorageMock is an autogenerated mock type for the ReservationStorage type
type ReservationStorageMock struct {
	mock.Mock
}

type ReservationStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ReservationStorageMock) EXPECT() *ReservationStorageMock_Expecter {
	return &ReservationStorageMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ReservationStorageMock
func (_mock *ReservationStorageMock) Create(ctx context.Context, reservation access.Reservation) (access.Reservation, error) {
	ret := _mock.Called(ctx, reservation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 access.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Reservation) (access.Reservation, error)); ok {
		return returnFunc(ctx, reservation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Reservation) access.Reservation); ok {
		r0 = returnFunc(ctx, reservation)
	} else {
		r0 = ret.Get(0).(access.Reservation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.Reservation) error); ok {
		r1 = returnFunc(ctx, reservation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReservationStorageMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReservationStorageMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reservation access.Reservation
func (_e *ReservationStorageMock_Expecter) Create(ctx interface{}, reservation interface{}) *ReservationStorageMock_Create_Call {
	return &ReservationStorageMock_Create_Call{Call: _e.mock.On("Create", ctx, reservation)}
}

func (_c *ReservationStorageMock_Create_Call) Run(run func(ctx context.Context, reservation access.Reservation)) *ReservationStorageMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.Reservation
		if args[1] != nil {
			arg1 = args[1].(access.Reservation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReservationStorageMock_Create_Call) Return(reservation1 access.Reservation, err error) *ReservationStorageMock_Create_Call {
	_c.Call.Return(reservation1, err)
	return _c
}

func (_c *ReservationStorageMock_Create_Call) RunAndReturn(run func(ctx context.Context, reservation access.Reservation) (access.Reservation, error)) *ReservationStorageMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByConfirmID provides a mock function for the type ReservationStorageMock
func (_mock *ReservationStorageMock) GetByConfirmID(ctx context.Context, confirmID string) (access.Reservation, error) {
	ret := _mock.Called(ctx, confirmID)

	if len(ret) == 0 {
		panic("no return value specified for GetByConfirmID")
	}

	var r0 access.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Reservation, error)); ok {
		return returnFunc(ctx, confirmID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Reservation); ok {
		r0 = returnFunc(ctx, confirmID)
	} else {
		r0 = ret.Get(0).(access.Reservation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, confirmID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReservationStorageMock_GetByConfirmID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByConfirmID'
type ReservationStorageMock_GetByConfirmID_Call struct {
	*mock.Call
}

// GetByConfirmID is a helper method to define mock.On call
//   - ctx context.Context
//   - confirmID string
func (_e *ReservationStorageMock_Expecter) GetByConfirmID(ctx interface{}, confirmID interface{}) *ReservationStorageMock_GetByConfirmID_Call {
	return &ReservationStorageMock_GetByConfirmID_Call{Call: _e.mock.On("GetByConfirmID", ctx, confirmID)}
}

func (_c *ReservationStorageMock_GetByConfirmID_Call) Run(run func(ctx context.Context, confirmID string)) *ReservationStorageMock_GetByConfirmID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReservationStorageMock_GetByConfirmID_Call) Return(reservation access.Reservation, err error) *ReservationStorageMock_GetByConfirmID_Call {
	_c.Call.Return(reservation, err)
	return _c
}

func (_c *ReservationStorageMock_GetByConfirmID_Call) RunAndReturn(run func(ctx context.Context, confirmID string) (access.Reservation, error)) *ReservationStorageMock_GetByConfirmID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ReservationStorageMock
func (_mock *ReservationStorageMock) GetByID(ctx context.Context, id string) (access.Reservation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 access.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Reservation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Reservation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(access.Reservation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReservationStorageMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ReservationStorageMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReservationStorageMock_Expecter) GetByID(ctx interface{}, id interface{}) *ReservationStorageMock_GetByID_Call {
	return &ReservationStorageMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ReservationStorageMock_GetByID_Call) Run(run func(ctx context.Context, id string)) *ReservationStorageMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReservationStorageMock_GetByID_Call) Return(reservation access.Reservation, err error) *ReservationStorageMock_GetByID_Call {
	_c.Call.Return(reservation, err)
	return _c
}

func (_c *ReservationStorageMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (access.Reservation, error)) *ReservationStorageMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type ReservationStorageMock
func (_mock *ReservationStorageMock) Release(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReservationStorageMock_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type ReservationStorageMock_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReservationStorageMock_Expecter) Release(ctx interface{}, id interface{}) *ReservationStorageMock_Release_Call {
	return &ReservationStorageMock_Release_Call{Call: _e.mock.On("Release", ctx, id)}
}

func (_c *ReservationStorageMock_Release_Call) Run(run func(ctx context.Context, id string)) *ReservationStorageMock_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReservationStorageMock_Release_Call) Return(err error) *ReservationStorageMock_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReservationStorageMock_Release_Call) RunAndReturn(run func(ctx context.Context, id string) error) *ReservationStorageMock_Release_Call {
	_c.Call.Return(run)
	return _c
}

// NewStockStorageMock creates a new instance of StockStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockStorageMock {
	mock := &StockStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StockStorageMock is an autogenerated mock type for the StockStorage type
type StockStorageMock struct {
	mock.Mock
}

type StockStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StockStorageMock) EXPECT() *StockStorageMock_Expecter {
	return &StockStorageMock_Expecter{mock: &_m.Mock}
}

// ConditionalDecrement provides a mock function for the type StockStorageMock
func (_mock *StockStorageMock) ConditionalDecrement(ctx context.Context, sku string, qty int) (int, error) {
	ret := _mock.Called(ctx, sku, qty)

	if len(ret) == 0 {
		panic("no return value specified for ConditionalDecrement")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (int, error)); ok {
		return returnFunc(ctx, sku, qty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) int); ok {
		r0 = returnFunc(ctx, sku, qty)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, sku, qty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockStorageMock_ConditionalDecrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConditionalDecrement'
type StockStorageMock_ConditionalDecrement_Call struct {
	*mock.Call
}

// ConditionalDecrement is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
//   - qty int
func (_e *StockStorageMock_Expecter) ConditionalDecrement(ctx interface{}, sku interface{}, qty interface{}) *StockStorageMock_ConditionalDecrement_Call {
	return &StockStorageMock_ConditionalDecrement_Call{Call: _e.mock.On("ConditionalDecrement", ctx, sku, qty)}
}

func (_c *StockStorageMock_ConditionalDecrement_Call) Run(run func(ctx context.Context, sku string, qty int)) *StockStorageMock_ConditionalDecrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StockStorageMock_ConditionalDecrement_Call) Return(n int, err error) *StockStorageMock_ConditionalDecrement_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *StockStorageMock_ConditionalDecrement_Call) RunAndReturn(run func(ctx context.Context, sku string, qty int) (int, error)) *StockStorageMock_ConditionalDecrement_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySKU provides a mock function for the type StockStorageMock
func (_mock *StockStorageMock) GetBySKU(ctx context.Context, sku string) (access.Stock, error) {
	ret := _mock.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetBySKU")
	}

	var r0 access.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Stock, error)); ok {
		return returnFunc(ctx, sku)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Stock); ok {
		r0 = returnFunc(ctx, sku)
	} else {
		r0 = ret.Get(0).(access.Stock)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockStorageMock_GetBySKU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySKU'
type StockStorageMock_GetBySKU_Call struct {
	*mock.Call
}

// GetBySKU is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
func (_e *StockStorageMock_Expecter) GetBySKU(ctx interface{}, sku interface{}) *StockStorageMock_GetBySKU_Call {
	return &StockStorageMock_GetBySKU_Call{Call: _e.mock.On("GetBySKU", ctx, sku)}
}

func (_c *StockStorageMock_GetBySKU_Call) Run(run func(ctx context.Context, sku string)) *StockStorageMock_GetBySKU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StockStorageMock_GetBySKU_Call) Return(stock access.Stock, err error) *StockStorageMock_GetBySKU_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *StockStorageMock_GetBySKU_Call) RunAndReturn(run func(ctx context.Context, sku string) (access.Stock, error)) *StockStorageMock_GetBySKU_Call {
	_c.Call.Return(run)
	return _c
}

// SetAvailable provides a mock function for the type StockStorageMock
func (_mock *StockStorageMock) SetAvailable(ctx context.Context, sku string, n int) error {
	ret := _mock.Called(ctx, sku, n)

	if len(ret) == 0 {
		panic("no return value specified for SetAvailable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, sku, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StockStorageMock_SetAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAvailable'
type StockStorageMock_SetAvailable_Call struct {
	*mock.Call
}

// SetAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
//   - n int
func (_e *StockStorageMock_Expecter) SetAvailable(ctx interface{}, sku interface{}, n interface{}) *StockStorageMock_SetAvailable_Call {
	return &StockStorageMock_SetAvailable_Call{Call: _e.mock.On("SetAvailable", ctx, sku, n)}
}

func (_c *StockStorageMock_SetAvailable_Call) Run(run func(ctx context.Context, sku string, n int)) *StockStorageMock_SetAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StockStorageMock_SetAvailable_Call) Return(err error) *StockStorageMock_SetAvailable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StockStorageMock_SetAvailable_Call) RunAndReturn(run func(ctx context.Context, sku string, n int) error) *StockStorageMock_SetAvailable_Call {
	_c.Call.Return(run)
	return _c
}
