// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/example-org/platform/backend/checkout/app/checkout/access"
)

// NewInventoryClientMock creates a new instance of InventoryClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClientMock {
	mock := &InventoryClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryClientMock is an autogenerated mock type for the InventoryClient type
type InventoryClientMock struct {
	mock.Mock
}

type InventoryClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClientMock) EXPECT() *InventoryClientMock_Expecter {
	return &InventoryClientMock_Expecter{mock: &_m.Mock}
}

// Reserve provides a mock function for the type InventoryClientMock
func (_mock *InventoryClientMock) Reserve(ctx context.Context, confirmID string, items []access.ReserveItem) (access.ReservationRef, error) {
	ret := _mock.Called(ctx, confirmID, items)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 access.ReservationRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []access.ReserveItem) (access.ReservationRef, error)); ok {
		return returnFunc(ctx, confirmID, items)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []access.ReserveItem) access.ReservationRef); ok {
		r0 = returnFunc(ctx, confirmID, items)
	} else {
		r0 = ret.Get(0).(access.ReservationRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []access.ReserveItem) error); ok {
		r1 = returnFunc(ctx, confirmID, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryClientMock_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type InventoryClientMock_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - confirmID string
//   - items []access.ReserveItem
func (_e *InventoryClientMock_Expecter) Reserve(ctx interface{}, confirmID interface{}, items interface{}) *InventoryClientMock_Reserve_Call {
	return &InventoryClientMock_Reserve_Call{Call: _e.mock.On("Reserve", ctx, confirmID, items)}
}

func (_c *InventoryClientMock_Reserve_Call) Run(run func(ctx context.Context, confirmID string, items []access.ReserveItem)) *InventoryClientMock_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []access.ReserveItem
		if args[2] != nil {
			arg2 = args[2].([]access.ReserveItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InventoryClientMock_Reserve_Call) Return(reservationRef access.ReservationRef, err error) *InventoryClientMock_Reserve_Call {
	_c.Call.Return(reservationRef, err)
	return _c
}

func (_c *InventoryClientMock_Reserve_Call) RunAndReturn(run func(ctx context.Context, confirmID string, items []access.ReserveItem) (access.ReservationRef, error)) *InventoryClientMock_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderClientMock creates a new instance of OrderClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderClientMock {
	mock := &OrderClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderClientMock is an autogenerated mock type for the OrderClient type
type OrderClientMock struct {
	mock.Mock
}

type OrderClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderClientMock) EXPECT() *OrderClientMock_Expecter {
	return &OrderClientMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderClientMock
func (_mock *OrderClientMock) Create(ctx context.Context, confirmID string, snapshot access.OrderSnapshot) (access.OrderRef, error) {
	ret := _mock.Called(ctx, confirmID, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 access.OrderRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, access.OrderSnapshot) (access.OrderRef, error)); ok {
		return returnFunc(ctx, confirmID, snapshot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, access.OrderSnapshot) access.OrderRef); ok {
		r0 = returnFunc(ctx, confirmID, snapshot)
	} else {
		r0 = ret.Get(0).(access.OrderRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, access.OrderSnapshot) error); ok {
		r1 = returnFunc(ctx, confirmID, snapshot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderClientMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderClientMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - confirmID string
//   - snapshot access.OrderSnapshot
func (_e *OrderClientMock_Expecter) Create(ctx interface{}, confirmID interface{}, snapshot interface{}) *OrderClientMock_Create_Call {
	return &OrderClientMock_Create_Call{Call: _e.mock.On("Create", ctx, confirmID, snapshot)}
}

func (_c *OrderClientMock_Create_Call) Run(run func(ctx context.Context, confirmID string, snapshot access.OrderSnapshot)) *OrderClientMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 access.OrderSnapshot
		if args[2] != nil {
			arg2 = args[2].(access.OrderSnapshot)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderClientMock_Create_Call) Return(orderRef access.OrderRef, err error) *OrderClientMock_Create_Call {
	_c.Call.Return(orderRef, err)
	return _c
}

func (_c *OrderClientMock_Create_Call) RunAndReturn(run func(ctx context.Context, confirmID string, snapshot access.OrderSnapshot) (access.OrderRef, error)) *OrderClientMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewPSPClientMock creates a new instance of PSPClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPSPClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PSPClientMock {
	mock := &PSPClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PSPClientMock is an autogenerated mock type for the PSPClient type
type PSPClientMock struct {
	mock.Mock
}

type PSPClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PSPClientMock) EXPECT() *PSPClientMock_Expecter {
	return &PSPClientMock_Expecter{mock: &_m.Mock}
}

// Capture provides a mock function for the type PSPClientMock
func (_mock *PSPClientMock) Capture(ctx context.Context, orderID string, amountMinor int, providerEventID string) (access.CaptureResult, error) {
	ret := _mock.Called(ctx, orderID, amountMinor, providerEventID)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 access.CaptureResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) (access.CaptureResult, error)); ok {
		return returnFunc(ctx, orderID, amountMinor, providerEventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) access.CaptureResult); ok {
		r0 = returnFunc(ctx, orderID, amountMinor, providerEventID)
	} else {
		r0 = ret.Get(0).(access.CaptureResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = returnFunc(ctx, orderID, amountMinor, providerEventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PSPClientMock_Capture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capture'
type PSPClientMock_Capture_Call struct {
	*mock.Call
}

// Capture is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - amountMinor int
//   - providerEventID string
func (_e *PSPClientMock_Expecter) Capture(ctx interface{}, orderID interface{}, amountMinor interface{}, providerEventID interface{}) *PSPClientMock_Capture_Call {
	return &PSPClientMock_Capture_Call{Call: _e.mock.On("Capture", ctx, orderID, amountMinor, providerEventID)}
}

func (_c *PSPClientMock_Capture_Call) Run(run func(ctx context.Context, orderID string, amountMinor int, providerEventID string)) *PSPClientMock_Capture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PSPClientMock_Capture_Call) Return(captureResult access.CaptureResult, err error) *PSPClientMock_Capture_Call {
	_c.Call.Return(captureResult, err)
	return _c
}

func (_c *PSPClientMock_Capture_Call) RunAndReturn(run func(ctx context.Context, orderID string, amountMinor int, providerEventID string) (access.CaptureResult, error)) *PSPClientMock_Capture_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditStorageMock creates a new instance of AuditStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditStorageMock {
	mock := &AuditStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditStorageMock is an autogenerated mock type for the AuditStorage type
type AuditStorageMock struct {
	mock.Mock
}

type AuditStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditStorageMock) EXPECT() *AuditStorageMock_Expecter {
	return &AuditStorageMock_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type AuditStorageMock
func (_mock *AuditStorageMock) Append(ctx context.Context, event access.AuditEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.AuditEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditStorageMock_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type AuditStorageMock_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event access.AuditEvent
func (_e *AuditStorageMock_Expecter) Append(ctx interface{}, event interface{}) *AuditStorageMock_Append_Call {
	return &AuditStorageMock_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *AuditStorageMock_Append_Call) Run(run func(ctx context.Context, event access.AuditEvent)) *AuditStorageMock_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(access.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditStorageMock_Append_Call) Return(err error) *AuditStorageMock_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditStorageMock_Append_Call) RunAndReturn(run func(ctx context.Context, event access.AuditEvent) error) *AuditStorageMock_Append_Call {
	_c.Call.Return(run)
	return _c
}

// NewCaptureStorageMock creates a new instance of CaptureStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaptureStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaptureStorageMock {
	mock := &CaptureStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CaptureStorageMock is an autogenerated mock type for the CaptureStorage type
type CaptureStorageMock struct {
	mock.Mock
}

type CaptureStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CaptureStorageMock) EXPECT() *CaptureStorageMock_Expecter {
	return &CaptureStorageMock_Expecter{mock: &_m.Mock}
}

// GetByProviderEventID provides a mock function for the type CaptureStorageMock
func (_mock *CaptureStorageMock) GetByProviderEventID(ctx context.Context, providerEventID string) (access.CaptureRecord, error) {
	ret := _mock.Called(ctx, providerEventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProviderEventID")
	}

	var r0 access.CaptureRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.CaptureRecord, error)); ok {
		return returnFunc(ctx, providerEventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.CaptureRecord); ok {
		r0 = returnFunc(ctx, providerEventID)
	} else {
		r0 = ret.Get(0).(access.CaptureRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, providerEventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaptureStorageMock_GetByProviderEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProviderEventID'
type CaptureStorageMock_GetByProviderEventID_Call struct {
	*mock.Call
}

// GetByProviderEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - providerEventID string
func (_e *CaptureStorageMock_Expecter) GetByProviderEventID(ctx interface{}, providerEventID interface{}) *CaptureStorageMock_GetByProviderEventID_Call {
	return &CaptureStorageMock_GetByProviderEventID_Call{Call: _e.mock.On("GetByProviderEventID", ctx, providerEventID)}
}

func (_c *CaptureStorageMock_GetByProviderEventID_Call) Run(run func(ctx context.Context, providerEventID string)) *CaptureStorageMock_GetByProviderEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CaptureStorageMock_GetByProviderEventID_Call) Return(captureRecord access.CaptureRecord, err error) *CaptureStorageMock_GetByProviderEventID_Call {
	_c.Call.Return(captureRecord, err)
	return _c
}

func (_c *CaptureStorageMock_GetByProviderEventID_Call) RunAndReturn(run func(ctx context.Context, providerEventID string) (access.CaptureRecord, error)) *CaptureStorageMock_GetByProviderEventID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderTotal provides a mock function for the type CaptureStorageMock
func (_mock *CaptureStorageMock) GetOrderTotal(ctx context.Context, orderID string) (int, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderTotal")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaptureStorageMock_GetOrderTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderTotal'
type CaptureStorageMock_GetOrderTotal_Call struct {
	*mock.Call
}

// GetOrderTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *CaptureStorageMock_Expecter) GetOrderTotal(ctx interface{}, orderID interface{}) *CaptureStorageMock_GetOrderTotal_Call {
	return &CaptureStorageMock_GetOrderTotal_Call{Call: _e.mock.On("GetOrderTotal", ctx, orderID)}
}

func (_c *CaptureStorageMock_GetOrderTotal_Call) Run(run func(ctx context.Context, orderID string)) *CaptureStorageMock_GetOrderTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CaptureStorageMock_GetOrderTotal_Call) Return(n int, err error) *CaptureStorageMock_GetOrderTotal_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CaptureStorageMock_GetOrderTotal_Call) RunAndReturn(run func(ctx context.Context, orderID string) (int, error)) *CaptureStorageMock_GetOrderTotal_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type CaptureStorageMock
func (_mock *CaptureStorageMock) Save(ctx context.Context, record access.CaptureRecord) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.CaptureRecord) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CaptureStorageMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CaptureStorageMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - record access.CaptureRecord
func (_e *CaptureStorageMock_Expecter) Save(ctx interface{}, record interface{}) *CaptureStorageMock_Save_Call {
	return &CaptureStorageMock_Save_Call{Call: _e.mock.On("Save", ctx, record)}
}

func (_c *CaptureStorageMock_Save_Call) Run(run func(ctx context.Context, record access.CaptureRecord)) *CaptureStorageMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.CaptureRecord
		if args[1] != nil {
			arg1 = args[1].(access.CaptureRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CaptureStorageMock_Save_Call) Return(err error) *CaptureStorageMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CaptureStorageMock_Save_Call) RunAndReturn(run func(ctx context.Context, record access.CaptureRecord) error) *CaptureStorageMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewCartStorageMock creates a new instance of CartStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartStorageMock {
	mock := &CartStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CartStorageMock is an autogenerated mock type for the CartStorage type
type CartStorageMock struct {
	mock.Mock
}

type CartStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CartStorageMock) EXPECT() *CartStorageMock_Expecter {
	return &CartStorageMock_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type CartStorageMock
func (_mock *CartStorageMock) GetByID(ctx context.Context, cartID string) (access.Cart, error) {
	ret := _mock.Called(ctx, cartID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 access.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Cart, error)); ok {
		return returnFunc(ctx, cartID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Cart); ok {
		r0 = returnFunc(ctx, cartID)
	} else {
		r0 = ret.Get(0).(access.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cartID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartStorageMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CartStorageMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - cartID string
func (_e *CartStorageMock_Expecter) GetByID(ctx interface{}, cartID interface{}) *CartStorageMock_GetByID_Call {
	return &CartStorageMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, cartID)}
}

func (_c *CartStorageMock_GetByID_Call) Run(run func(ctx context.Context, cartID string)) *CartStorageMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartStorageMock_GetByID_Call) Return(cart access.Cart, err error) *CartStorageMock_GetByID_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *CartStorageMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, cartID string) (access.Cart, error)) *CartStorageMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewCouponStorageMock creates a new instance of CouponStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponStorageMock {
	mock := &CouponStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CouponStorageMock is an autogenerated mock type for the CouponStorage type
type CouponStorageMock struct {
	mock.Mock
}

type CouponStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CouponStorageMock) EXPECT() *CouponStorageMock_Expecter {
	return &CouponStorageMock_Expecter{mock: &_m.Mock}
}

// GetByCode provides a mock function for the type CouponStorageMock
func (_mock *CouponStorageMock) GetByCode(ctx context.Context, code string) (access.Coupon, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 access.Coupon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Coupon, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Coupon); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(access.Coupon)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CouponStorageMock_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type CouponStorageMock_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *CouponStorageMock_Expecter) GetByCode(ctx interface{}, code interface{}) *CouponStorageMock_GetByCode_Call {
	return &CouponStorageMock_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *CouponStorageMock_GetByCode_Call) Run(run func(ctx context.Context, code string)) *CouponStorageMock_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponStorageMock_GetByCode_Call) Return(coupon access.Coupon, err error) *CouponStorageMock_GetByCode_Call {
	_c.Call.Return(coupon, err)
	return _c
}

func (_c *CouponStorageMock_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (access.Coupon, error)) *CouponStorageMock_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdempotencyStorageMock creates a new instance of IdempotencyStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdempotencyStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdempotencyStorageMock {
	mock := &IdempotencyStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdempotencyStorageMock is an autogenerated mock type for the IdempotencyStorage type
type IdempotencyStorageMock struct {
	mock.Mock
}

type IdempotencyStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *IdempotencyStorageMock) EXPECT() *IdempotencyStorageMock_Expecter {
	return &IdempotencyStorageMock_Expecter{mock: &_m.Mock}
}

// GetByKey provides a mock function for the type IdempotencyStorageMock
func (_mock *IdempotencyStorageMock) GetByKey(ctx context.Context, key string) (access.IdempotencyRecord, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 access.IdempotencyRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.IdempotencyRecord, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.IdempotencyRecord); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(access.IdempotencyRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdempotencyStorageMock_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type IdempotencyStorageMock_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *IdempotencyStorageMock_Expecter) GetByKey(ctx interface{}, key interface{}) *IdempotencyStorageMock_GetByKey_Call {
	return &IdempotencyStorageMock_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, key)}
}

func (_c *IdempotencyStorageMock_GetByKey_Call) Run(run func(ctx context.Context, key string)) *IdempotencyStorageMock_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdempotencyStorageMock_GetByKey_Call) Return(idempotencyRecord access.IdempotencyRecord, err error) *IdempotencyStorageMock_GetByKey_Call {
	_c.Call.Return(idempotencyRecord, err)
	return _c
}

func (_c *IdempotencyStorageMock_GetByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (access.IdempotencyRecord, error)) *IdempotencyStorageMock_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type IdempotencyStorageMock
func (_mock *IdempotencyStorageMock) Save(ctx context.Context, record access.IdempotencyRecord) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.IdempotencyRecord) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IdempotencyStorageMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type IdempotencyStorageMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - record access.IdempotencyRecord
func (_e *IdempotencyStorageMock_Expecter) Save(ctx interface{}, record interface{}) *IdempotencyStorageMock_Save_Call {
	return &IdempotencyStorageMock_Save_Call{Call: _e.mock.On("Save", ctx, record)}
}

func (_c *IdempotencyStorageMock_Save_Call) Run(run func(ctx context.Context, record access.IdempotencyRecord)) *IdempotencyStorageMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.IdempotencyRecord
		if args[1] != nil {
			arg1 = args[1].(access.IdempotencyRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdempotencyStorageMock_Save_Call) Return(err error) *IdempotencyStorageMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IdempotencyStorageMock_Save_Call) RunAndReturn(run func(ctx context.Context, record access.IdempotencyRecord) error) *IdempotencyStorageMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutboxStorageMock creates a new instance of OutboxStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxStorageMock {
	mock := &OutboxStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OutboxStorageMock is an autogenerated mock type for the OutboxStorage type
type OutboxStorageMock struct {
	mock.Mock
}

type OutboxStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxStorageMock) EXPECT() *OutboxStorageMock_Expecter {
	return &OutboxStorageMock_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type OutboxStorageMock
func (_mock *OutboxStorageMock) Append(ctx context.Context, event access.OutboxEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.OutboxEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxStorageMock_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type OutboxStorageMock_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event access.OutboxEvent
func (_e *OutboxStorageMock_Expecter) Append(ctx interface{}, event interface{}) *OutboxStorageMock_Append_Call {
	return &OutboxStorageMock_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *OutboxStorageMock_Append_Call) Run(run func(ctx context.Context, event access.OutboxEvent)) *OutboxStorageMock_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.OutboxEvent
		if args[1] != nil {
			arg1 = args[1].(access.OutboxEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OutboxStorageMock_Append_Call) Return(err error) *OutboxStorageMock_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxStorageMock_Append_Call) RunAndReturn(run func(ctx context.Context, event access.OutboxEvent) error) *OutboxStorageMock_Append_Call {
	_c.Call.Return(run)
	return _c
}
