// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/example-org/platform/backend/order/app/order/access"
)

// NewAuditStorageMock creates a new instance of AuditStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditStorageMock {
	mock := &AuditStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditStorageMock is an autogenerated mock type for the AuditStorage type
type AuditStorageMock struct {
	mock.Mock
}

type AuditStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditStorageMock) EXPECT() *AuditStorageMock_Expecter {
	return &AuditStorageMock_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type AuditStorageMock
func (_mock *AuditStorageMock) Append(ctx context.Context, event access.AuditEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.AuditEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditStorageMock_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type AuditStorageMock_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event access.AuditEvent
func (_e *AuditStorageMock_Expecter) Append(ctx interface{}, event interface{}) *AuditStorageMock_Append_Call {
	return &AuditStorageMock_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *AuditStorageMock_Append_Call) Run(run func(ctx context.Context, event access.AuditEvent)) *AuditStorageMock_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(access.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditStorageMock_Append_Call) Return(err error) *AuditStorageMock_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditStorageMock_Append_Call) RunAndReturn(run func(ctx context.Context, event access.AuditEvent) error) *AuditStorageMock_Append_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderStorageMock creates a new instance of OrderStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderStorageMock {
	mock := &OrderStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderStorageMock is an autogenerated mock type for the OrderStorage type
type OrderStorageMock struct {
	mock.Mock
}

type OrderStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderStorageMock) EXPECT() *OrderStorageMock_Expecter {
	return &OrderStorageMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderStorageMock
func (_mock *OrderStorageMock) Create(ctx context.Context, order access.Order) (access.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 access.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Order) (access.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.Order) access.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Get(0).(access.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderStorageMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderStorageMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order access.Order
func (_e *OrderStorageMock_Expecter) Create(ctx interface{}, order interface{}) *OrderStorageMock_Create_Call {
	return &OrderStorageMock_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderStorageMock_Create_Call) Run(run func(ctx context.Context, order access.Order)) *OrderStorageMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.Order
		if args[1] != nil {
			arg1 = args[1].(access.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderStorageMock_Create_Call) Return(order1 access.Order, err error) *OrderStorageMock_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *OrderStorageMock_Create_Call) RunAndReturn(run func(ctx context.Context, order access.Order) (access.Order, error)) *OrderStorageMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByConfirmID provides a mock function for the type OrderStorageMock
func (_mock *OrderStorageMock) GetByConfirmID(ctx context.Context, confirmID string) (access.Order, error) {
	ret := _mock.Called(ctx, confirmID)

	if len(ret) == 0 {
		panic("no return value specified for GetByConfirmID")
	}

	var r0 access.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Order, error)); ok {
		return returnFunc(ctx, confirmID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Order); ok {
		r0 = returnFunc(ctx, confirmID)
	} else {
		r0 = ret.Get(0).(access.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, confirmID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderStorageMock_GetByConfirmID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByConfirmID'
type OrderStorageMock_GetByConfirmID_Call struct {
	*mock.Call
}

// GetByConfirmID is a helper method to define mock.On call
//   - ctx context.Context
//   - confirmID string
func (_e *OrderStorageMock_Expecter) GetByConfirmID(ctx interface{}, confirmID interface{}) *OrderStorageMock_GetByConfirmID_Call {
	return &OrderStorageMock_GetByConfirmID_Call{Call: _e.mock.On("GetByConfirmID", ctx, confirmID)}
}

func (_c *OrderStorageMock_GetByConfirmID_Call) Run(run func(ctx context.Context, confirmID string)) *OrderStorageMock_GetByConfirmID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderStorageMock_GetByConfirmID_Call) Return(order access.Order, err error) *OrderStorageMock_GetByConfirmID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderStorageMock_GetByConfirmID_Call) RunAndReturn(run func(ctx context.Context, confirmID string) (access.Order, error)) *OrderStorageMock_GetByConfirmID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrderNo provides a mock function for the type OrderStorageMock
func (_mock *OrderStorageMock) GetByOrderNo(ctx context.Context, orderNo string) (access.Order, error) {
	ret := _mock.Called(ctx, orderNo)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderNo")
	}

	var r0 access.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Order, error)); ok {
		return returnFunc(ctx, orderNo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Order); ok {
		r0 = returnFunc(ctx, orderNo)
	} else {
		r0 = ret.Get(0).(access.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderStorageMock_GetByOrderNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderNo'
type OrderStorageMock_GetByOrderNo_Call struct {
	*mock.Call
}

// GetByOrderNo is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNo string
func (_e *OrderStorageMock_Expecter) GetByOrderNo(ctx interface{}, orderNo interface{}) *OrderStorageMock_GetByOrderNo_Call {
	return &OrderStorageMock_GetByOrderNo_Call{Call: _e.mock.On("GetByOrderNo", ctx, orderNo)}
}

func (_c *OrderStorageMock_GetByOrderNo_Call) Run(run func(ctx context.Context, orderNo string)) *OrderStorageMock_GetByOrderNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderStorageMock_GetByOrderNo_Call) Return(order access.Order, err error) *OrderStorageMock_GetByOrderNo_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderStorageMock_GetByOrderNo_Call) RunAndReturn(run func(ctx context.Context, orderNo string) (access.Order, error)) *OrderStorageMock_GetByOrderNo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function for the type OrderStorageMock
func (_mock *OrderStorageMock) UpdateState(ctx context.Context, orderNo string, state string, trackingNo string) error {
	ret := _mock.Called(ctx, orderNo, state, trackingNo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, orderNo, state, trackingNo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderStorageMock_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type OrderStorageMock_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNo string
//   - state string
//   - trackingNo string
func (_e *OrderStorageMock_Expecter) UpdateState(ctx interface{}, orderNo interface{}, state interface{}, trackingNo interface{}) *OrderStorageMock_UpdateState_Call {
	return &OrderStorageMock_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, orderNo, state, trackingNo)}
}

func (_c *OrderStorageMock_UpdateState_Call) Run(run func(ctx context.Context, orderNo string, state string, trackingNo string)) *OrderStorageMock_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OrderStorageMock_UpdateState_Call) Return(err error) *OrderStorageMock_UpdateState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderStorageMock_UpdateState_Call) RunAndReturn(run func(ctx context.Context, orderNo string, state string, trackingNo string) error) *OrderStorageMock_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutboxStorageMock creates a new instance of OutboxStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxStorageMock {
	mock := &OutboxStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OutboxStorageMock is an autogenerated mock type for the OutboxStorage type
type OutboxStorageMock struct {
	mock.Mock
}

type OutboxStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxStorageMock) EXPECT() *OutboxStorageMock_Expecter {
	return &OutboxStorageMock_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type OutboxStorageMock
func (_mock *OutboxStorageMock) Append(ctx context.Context, event access.OutboxEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.OutboxEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxStorageMock_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type OutboxStorageMock_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event access.OutboxEvent
func (_e *OutboxStorageMock_Expecter) Append(ctx interface{}, event interface{}) *OutboxStorageMock_Append_Call {
	return &OutboxStorageMock_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *OutboxStorageMock_Append_Call) Run(run func(ctx context.Context, event access.OutboxEvent)) *OutboxStorageMock_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.OutboxEvent
		if args[1] != nil {
			arg1 = args[1].(access.OutboxEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OutboxStorageMock_Append_Call) Return(err error) *OutboxStorageMock_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxStorageMock_Append_Call) RunAndReturn(run func(ctx context.Context, event access.OutboxEvent) error) *OutboxStorageMock_Append_Call {
	_c.Call.Return(run)
	return _c
}
