// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package access_mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/example-org/platform/backend/auth/app/auth/access"
)

// NewAuditStorageMock creates a new instance of AuditStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditStorageMock {
	mock := &AuditStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditStorageMock is an autogenerated mock type for the AuditStorage type
type AuditStorageMock struct {
	mock.Mock
}

type AuditStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditStorageMock) EXPECT() *AuditStorageMock_Expecter {
	return &AuditStorageMock_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type AuditStorageMock
func (_mock *AuditStorageMock) Append(ctx context.Context, event access.AuditEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.AuditEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditStorageMock_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type AuditStorageMock_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event access.AuditEvent
func (_e *AuditStorageMock_Expecter) Append(ctx interface{}, event interface{}) *AuditStorageMock_Append_Call {
	return &AuditStorageMock_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *AuditStorageMock_Append_Call) Run(run func(ctx context.Context, event access.AuditEvent)) *AuditStorageMock_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(access.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditStorageMock_Append_Call) Return(err error) *AuditStorageMock_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditStorageMock_Append_Call) RunAndReturn(run func(ctx context.Context, event access.AuditEvent) error) *AuditStorageMock_Append_Call {
	_c.Call.Return(run)
	return _c
}

// NewCredentialStorageMock creates a new instance of CredentialStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialStorageMock {
	mock := &CredentialStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialStorageMock is an autogenerated mock type for the CredentialStorage type
type CredentialStorageMock struct {
	mock.Mock
}

type CredentialStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialStorageMock) EXPECT() *CredentialStorageMock_Expecter {
	return &CredentialStorageMock_Expecter{mock: &_m.Mock}
}

// GetByEmailHash provides a mock function for the type CredentialStorageMock
func (_mock *CredentialStorageMock) GetByEmailHash(ctx context.Context, emailHash string) (access.Credential, error) {
	ret := _mock.Called(ctx, emailHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmailHash")
	}

	var r0 access.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.Credential, error)); ok {
		return returnFunc(ctx, emailHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.Credential); ok {
		r0 = returnFunc(ctx, emailHash)
	} else {
		r0 = ret.Get(0).(access.Credential)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, emailHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CredentialStorageMock_GetByEmailHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmailHash'
type CredentialStorageMock_GetByEmailHash_Call struct {
	*mock.Call
}

// GetByEmailHash is a helper method to define mock.On call
//   - ctx context.Context
//   - emailHash string
func (_e *CredentialStorageMock_Expecter) GetByEmailHash(ctx interface{}, emailHash interface{}) *CredentialStorageMock_GetByEmailHash_Call {
	return &CredentialStorageMock_GetByEmailHash_Call{Call: _e.mock.On("GetByEmailHash", ctx, emailHash)}
}

func (_c *CredentialStorageMock_GetByEmailHash_Call) Run(run func(ctx context.Context, emailHash string)) *CredentialStorageMock_GetByEmailHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CredentialStorageMock_GetByEmailHash_Call) Return(credential access.Credential, err error) *CredentialStorageMock_GetByEmailHash_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *CredentialStorageMock_GetByEmailHash_Call) RunAndReturn(run func(ctx context.Context, emailHash string) (access.Credential, error)) *CredentialStorageMock_GetByEmailHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenFamilyStorageMock creates a new instance of TokenFamilyStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenFamilyStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenFamilyStorageMock {
	mock := &TokenFamilyStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenFamilyStorageMock is an autogenerated mock type for the TokenFamilyStorage type
type TokenFamilyStorageMock struct {
	mock.Mock
}

type TokenFamilyStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenFamilyStorageMock) EXPECT() *TokenFamilyStorageMock_Expecter {
	return &TokenFamilyStorageMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TokenFamilyStorageMock
func (_mock *TokenFamilyStorageMock) Create(ctx context.Context, fam access.TokenFamily) (access.TokenFamily, error) {
	ret := _mock.Called(ctx, fam)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 access.TokenFamily
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.TokenFamily) (access.TokenFamily, error)); ok {
		return returnFunc(ctx, fam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, access.TokenFamily) access.TokenFamily); ok {
		r0 = returnFunc(ctx, fam)
	} else {
		r0 = ret.Get(0).(access.TokenFamily)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, access.TokenFamily) error); ok {
		r1 = returnFunc(ctx, fam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenFamilyStorageMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TokenFamilyStorageMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - fam access.TokenFamily
func (_e *TokenFamilyStorageMock_Expecter) Create(ctx interface{}, fam interface{}) *TokenFamilyStorageMock_Create_Call {
	return &TokenFamilyStorageMock_Create_Call{Call: _e.mock.On("Create", ctx, fam)}
}

func (_c *TokenFamilyStorageMock_Create_Call) Run(run func(ctx context.Context, fam access.TokenFamily)) *TokenFamilyStorageMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 access.TokenFamily
		if args[1] != nil {
			arg1 = args[1].(access.TokenFamily)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenFamilyStorageMock_Create_Call) Return(tokenFamily access.TokenFamily, err error) *TokenFamilyStorageMock_Create_Call {
	_c.Call.Return(tokenFamily, err)
	return _c
}

func (_c *TokenFamilyStorageMock_Create_Call) RunAndReturn(run func(ctx context.Context, fam access.TokenFamily) (access.TokenFamily, error)) *TokenFamilyStorageMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRefreshHash provides a mock function for the type TokenFamilyStorageMock
func (_mock *TokenFamilyStorageMock) GetByRefreshHash(ctx context.Context, refreshHash string) (access.TokenFamily, error) {
	ret := _mock.Called(ctx, refreshHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByRefreshHash")
	}

	var r0 access.TokenFamily
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (access.TokenFamily, error)); ok {
		return returnFunc(ctx, refreshHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) access.TokenFamily); ok {
		r0 = returnFunc(ctx, refreshHash)
	} else {
		r0 = ret.Get(0).(access.TokenFamily)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenFamilyStorageMock_GetByRefreshHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRefreshHash'
type TokenFamilyStorageMock_GetByRefreshHash_Call struct {
	*mock.Call
}

// GetByRefreshHash is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshHash string
func (_e *TokenFamilyStorageMock_Expecter) GetByRefreshHash(ctx interface{}, refreshHash interface{}) *TokenFamilyStorageMock_GetByRefreshHash_Call {
	return &TokenFamilyStorageMock_GetByRefreshHash_Call{Call: _e.mock.On("GetByRefreshHash", ctx, refreshHash)}
}

func (_c *TokenFamilyStorageMock_GetByRefreshHash_Call) Run(run func(ctx context.Context, refreshHash string)) *TokenFamilyStorageMock_GetByRefreshHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenFamilyStorageMock_GetByRefreshHash_Call) Return(tokenFamily access.TokenFamily, err error) *TokenFamilyStorageMock_GetByRefreshHash_Call {
	_c.Call.Return(tokenFamily, err)
	return _c
}

func (_c *TokenFamilyStorageMock_GetByRefreshHash_Call) RunAndReturn(run func(ctx context.Context, refreshHash string) (access.TokenFamily, error)) *TokenFamilyStorageMock_GetByRefreshHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeFamily provides a mock function for the type TokenFamilyStorageMock
func (_mock *TokenFamilyStorageMock) RevokeFamily(ctx context.Context, familyID string) error {
	ret := _mock.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, familyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenFamilyStorageMock_RevokeFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeFamily'
type TokenFamilyStorageMock_RevokeFamily_Call struct {
	*mock.Call
}

// RevokeFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID string
func (_e *TokenFamilyStorageMock_Expecter) RevokeFamily(ctx interface{}, familyID interface{}) *TokenFamilyStorageMock_RevokeFamily_Call {
	return &TokenFamilyStorageMock_RevokeFamily_Call{Call: _e.mock.On("RevokeFamily", ctx, familyID)}
}

func (_c *TokenFamilyStorageMock_RevokeFamily_Call) Run(run func(ctx context.Context, familyID string)) *TokenFamilyStorageMock_RevokeFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenFamilyStorageMock_RevokeFamily_Call) Return(err error) *TokenFamilyStorageMock_RevokeFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenFamilyStorageMock_RevokeFamily_Call) RunAndReturn(run func(ctx context.Context, familyID string) error) *TokenFamilyStorageMock_RevokeFamily_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type TokenFamilyStorageMock
func (_mock *TokenFamilyStorageMock) Rotate(ctx context.Context, familyID string, newRefreshHash string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, familyID, newRefreshHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, familyID, newRefreshHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenFamilyStorageMock_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type TokenFamilyStorageMock_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID string
//   - newRefreshHash string
//   - expiresAt time.Time
func (_e *TokenFamilyStorageMock_Expecter) Rotate(ctx interface{}, familyID interface{}, newRefreshHash interface{}, expiresAt interface{}) *TokenFamilyStorageMock_Rotate_Call {
	return &TokenFamilyStorageMock_Rotate_Call{Call: _e.mock.On("Rotate", ctx, familyID, newRefreshHash, expiresAt)}
}

func (_c *TokenFamilyStorageMock_Rotate_Call) Run(run func(ctx context.Context, familyID string, newRefreshHash string, expiresAt time.Time)) *TokenFamilyStorageMock_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenFamilyStorageMock_Rotate_Call) Return(err error) *TokenFamilyStorageMock_Rotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenFamilyStorageMock_Rotate_Call) RunAndReturn(run func(ctx context.Context, familyID string, newRefreshHash string, expiresAt time.Time) error) *TokenFamilyStorageMock_Rotate_Call {
	_c.Call.Return(run)
	return _c
}
